apiVersion: v1
kind: Pod
metadata:
  name: client-deploy
  namespace: fedlearn
  labels:
    app: client
    purpose: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      purpose: example
  template:
    metadata:
      labels:
        app: client
        purpose: example
    spec:
      containers:
      - name: client
        image: raselc/acnmo:fl
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c","python"]
        resources:
          limits:
            cpu: "1"
            memory: "700Mi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        ports:
        - containerPort: 5010
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: client-svc
  namespace: fedlearn
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
