apiVersion: apps/v1
kind: Deployment
metadata:
  name: flk8-deploy
  namespace: fedlearn
  labels:
    app: fl-server
    purpose: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-server
      purpose: example
  template:
    metadata:
      labels:
        app: fl-server
        purpose: example
    spec:
      containers:
      - name: fl-server
        image: raselc/acnmo:fl
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c","python /app/Server/fl_server.py"]
        resources:
          limits:
            cpu: "1"
            memory: "700Mi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: flk8-svc
  namespace: fedlearn
spec:
  selector:
    app: fl-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
