apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: fedlearn
  labels:
    app: server
    purpose: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      purpose: example
  template:
    metadata:
      labels:
        app: server
        purpose: example
    spec:
      containers:
      - name: server
        image: raselc/acnmo:fl
        imagePullPolicy: Always
        #command: ["/bin/sh"]
        args: [bash, -c,'for ((i-0;;i++)); do echo "hello";sleep 2000;done']
        resources:
          limits:
            cpu: "1"
            memory: "700Mi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: fedlearn
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
