apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orches-role
  namespace: orchestration
rules:
- apiGroup: [""]
  resources:
  - pods
  - services
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orches-role
  namespace: orchestration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orches-role
subjects:
- kind: ServiceAccount
  name: orches-role
  namespace: orchestration